### ISSUE TITLE
great app. how does one show (not type) password/info of an entry in dmenu?

### ISSUE THREAD

**Issue by zeltak** [Evidlo/passhole#11]
Hi!

this is really great. i cant seem to figure out how to show (not type) password/info of an entry in dmenu?

i can easily copy the password via dmenu using this command

```
 ph --database ~/apps/ZPasswords.kdbx type dmenu
```

but how can one show (in demnu) a entry?

thx alot!

Z

**Comment by Evidlo** [comment]
The dmenu integration is for typing only. See firecat53/keepmenu.

On Oct 25, 2018 4:50 AM, "zeltak" <notifications@github.com> wrote:

Hi!

this is really great. i cant seem to figure out how to show (not type)
password/info of an entry in dmenu?

i can easily copy the password via dmenu using this command

 ph --database ~/apps/ZPasswords.kdbx type dmenu

but how can one show (in demnu) a entry?

thx alot!

Z

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Evidlo/passhole/issues/11>, or mute the thread

**Comment by zeltak** [comment]
moved to keepmenu thx for the tip!
